quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=product00
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:54330/product

quarkus.hibernate-orm.database.default-schema=product
quarkus.hibernate-orm.database.generation=validate
