openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /v1/order:
    post:
      tags:
      - Order
      operationId: addOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PurchaseOrderDto"
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseOrderIdDto"
  /v1/orders:
    get:
      tags:
      - Order
      operationId: findAllOrders
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PurchaseOrderDto"
  /v1/order/{id}:
    delete:
      tags:
      - Order
      operationId: deleteOrder
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
        "200":
          description: OK
components:
  schemas:
    ErrorResponseDto:
      type: object
      properties:
        errorMessage:
          type: string
        timestamp:
          type: string
          format: date-time
    PurchaseOrderDto:
      type: object
      properties:
        purchaseOrderId:
          type: integer
          format: int64
        clientId:
          type: integer
          format: int64
        totalAmount:
          type: number
        purchaseOrderItems:
          type: array
          items:
            $ref: "#/components/schemas/PurchaseOrderItemDto"
          minItems: 1
      required:
      - clientId
      - purchaseOrderItems
    PurchaseOrderItemDto:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: number
        priceItem:
          type: number
        totalPrice:
          type: number
      required:
      - productId
      - quantity
    PurchaseOrderIdDto:
      type: object
      properties:
        purchaseOrderId:
          type: integer
          format: int64
