CREATE SCHEMA IF NOT EXISTS product;

CREATE TABLE IF not EXISTS product.product
(
    id                 bigint generated BY DEFAULT AS identity NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    unit_price         DECIMAL(10, 2)                          NOT NULL,
    quantity_total     DECIMAL(10, 3)                          NOT NULL,
    quantity_reserved  DECIMAL(10, 3),
    created_date       timestamptz                             NOT NULL,
    updated_date       timestamptz,
    CONSTRAINT product_pk PRIMARY KEY (id)
    );

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Ocun Vision WR 9.1 mm 60 m', 1119.99, 10, 2, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Edelrid Boa 9,8 mm 60 m - red', 624.99, 50, 4, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Beal Cobra Unicore Dry Cover 8,6 mm 60 m - blue', 739.99, 32, 1, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Tendon Smart Lite 9,8 mm 60 m - green', 534.99, 20, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Fixe Climbing Rocco 10,0 60 m - blue', 704.99, 56, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Mammut 9.8 Crag Dry Rope 60 m - safety orange/boa', 934.99, 13, 2, now(), null);